--- #YAML:1.0
name:               Catalyst-Model-SOAP
version:            1.4
abstract:           Map a WSDL to a catalyst model class.
author:
    - Daniel Ruoso <daniel@ruoso.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Runtime:   5.7011
    Moose:               0.9
    XML::Compile:        1.06
    XML::Compile::SOAP:  2.07
    XML::LibXML:         1.7
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
