# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-SOAP
version:      0.0.6
version_from: lib/Catalyst/Model/SOAP.pm
installdirs:  site
requires:
    Catalyst::Runtime:             5.7011
    XML::Compile::SOAP:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
